### ISSUE TITLE
Sidebar should be scrollable

### ISSUE THREAD

**Issue by SayanDeveloper** [Pizza-Wallet-Development-team/pizza-wallet#52]
Issue :- The Sidebar is overflowing for 768p screen and the history tab is not visible.

Screenshot :- 
![image](https://user-images.githubusercontent.com/67837886/188736925-5084523b-ac3e-45aa-b1a7-08c1be7a1c2d.png)

Fixes :- 
If we will apply scrollable sidebar then it would be more interactive and the issue can be solved or else we have to reduce fonts and sizes

**Comment by nunocgoncalves** [comment]
Hi @SayanDeveloper! Thank you for your contribution!

We fixed this issue in PR #46
You can check the live preview here: [link](https://bafybeianw5pmwjqe7yb7isd63clrhkd2nqpwuaucdcq3jzmgm4jsllcqme.on.fleek.co/)

If you're interested in making other contributions feel free to email me at nunogoncalves@mercurylabs.xyz or contact me in Discord at nunomiguelcg#9270

**Comment by SayanDeveloper** [comment]
Okay sure. You can also contact me for assigning any task for frontend. I am ready to contribute.
My discord id: juniorserpent12#4220
