### ISSUE TITLE
Error: pizza auth error (possible caused by onramp integration)

### ISSUE THREAD

**Issue by peteruche21** [Pizza-Wallet-Development-team/pizza-wallet#59]
app is not successfully compiled while running development server
```
Module parse failed: Identifier directly after number (124:21)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     supportPage: "https://help.moonpay.io/en/",
|     minOrderValue: 24.99,
>     maxOrderValue: 50_000,
|     validCurrencies: supportedFiatCurrencies(PAYMENT_PROVIDER.MOONPAY),
|     validCryptoCurrenciesByChain: {
```

1. `git clone this reposotory`
2. `cd pizza-wallet`
3. `yarn install`
4. set moralis APP_ID and SERVER_URL in a `.env` file
5. `yarn start`

**Expected behavior**
app is meant to compile successfully.

**Screenshots**
![error-pizza](https://user-images.githubusercontent.com/53627398/191977306-1aabe5e7-d4e6-4600-bc4a-75c78d8c2be0.png)

**Desktop**
 - OS: ubuntu focal 20.4
 - Browser: brave
 - version: [Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)](https://brave.com/latest/)

**node**
engine: v16.17.0
npm: v8.15.0

**Additional context**
unfortunately this error may probaly be present in prod hence [page not displaying](https://app.pizzawallet.io/#/onramper)

**Comment by gitChimp88** [comment]
I upgraded the project to use react-scripts 5 and it fixed the compilation error, pr is here -https://github.com/Pizza-Wallet-Development-team/pizza-wallet/pull/62
