### ISSUE TITLE
[Dashboard]: "Buy tokens" button is only visible on unsupported chains

### ISSUE THREAD

**Issue by vaib-ag** [Pizza-Wallet-Development-team/pizza-wallet#75]
**Describe the bug**
"Buy token" button in Tokens table under Dashboard is ONLY visible for the unsupported chains. For the 
supported chains, it does not appear. 

**To Reproduce**
1> login through metamask
2> Select a chain which is **supported** by pizza wallet
3> Make sure that selected wallet address used should not have any tokens or native coins on that chain
4> Observer that the "Buy token" button does not appear
5> Switch chain in metamask to the one which is **not supoorted** by pizza wallet
6> Observe that the "Buy token" button appears here

**Screenshots**
![image](https://user-images.githubusercontent.com/48979975/195360359-e905cf94-59a9-47b6-8b47-424ecfb4476a.png)

**Comment by gitChimp88** [comment]
Alright I made a pr fixing this one - https://github.com/Pizza-Wallet-Development-team/pizza-wallet/pull/77

**Comment by nunocgoncalves** [comment]
Fixed on PR #77
