### ISSUE TITLE
[Login]: "Can not execute moralis" error encountered on social login - #3u46kvf

### ISSUE THREAD

**Issue by vaib-ag** [Pizza-Wallet-Development-team/pizza-wallet#76]
**Describe the bug**
When you click on "social login" and close the "sign-in" popup, after that everytime clicking on "social login" button leads to error, unless user refresh the page. 

**To Reproduce**
1. Open https://app.pizzawallet.io/
2. Click "social login" button
3. "sign-in" pop-up is displayed
4. close this pop-up without selecting any social login. 
5. Click on "social login" button again.
6. observer that the following error message is displayed
**_"Cannot execute Moralis.enableWeb3(), as Moralis Moralis.enableWeb3() already has been called, but is not finished yet "_**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48979975/195529606-f5b8c71f-bc36-4ced-9dd7-c56e11070fe8.png)

**Comment by nunocgoncalves** [comment]
It looks like we're not saving ``isAuthenticating`` in state for the Web3Auth Sign in function. Once that's done, we can put a condition in place which allows us to verify it has already been called or not.
This will be fixed today.

**Comment by nunocgoncalves** [comment]
Will close this issue as Moralis will soon be deprecated.
