### ISSUE TITLE
App is not redirected to landing page if connection is timed out and user tries to refresh the dashboard

### ISSUE THREAD

**Issue by vaib-ag** [Pizza-Wallet-Development-team/pizza-wallet#78]
If a user's connection timesout and user tries to refresh the page, dashboard page is still displayed and social login popup is displayed.
Rather application should redirect the user to the landing page from where user should restart the journy.

**To Reproduce**
1. do Social login
2. leave open dashboard page for the time it takes for auto session logout (I revisted the page after around a day)
3. Refresh the page
4. Observe the behaviour described.

**Screenshots**
![image](https://user-images.githubusercontent.com/48979975/196113889-c8925f6a-1172-43ec-90ac-b3f7049f364a.png)

**Comment by nunocgoncalves** [comment]
This looks like a state management problem. Still not quite sure what the problem is.
@gitChimp88, could you take a look?

**Comment by gitChimp88** [comment]
I think I may have fixed it with the below pr, looks like useMoralis returns isAuthenticated - true but doesn't have a value for account so I put a check for both of those values when deciding where to re-direct.
https://github.com/Pizza-Wallet-Development-team/pizza-wallet/pull/81
